import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../engagement/data/engagement_repository.dart';
import '../../../core/network/api_client.dart';
import '../domain/flash.dart';
class FlashDetailPage extends ConsumerStatefulWidget{const FlashDetailPage({super.key,required this.flash});final Flash flash;@override ConsumerState<FlashDetailPage> createState()=>_FlashDetailPageState();}
class _FlashDetailPageState extends ConsumerState<FlashDetailPage>{bool helpful=false;bool busy=false;Future<void> react(bool share)async{setState(()=>busy=true);try{final repo=EngagementRepository(ref.read(apiClientProvider));if(share){await repo.recordShare(widget.flash.id);if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Share recorded.')));}else{if(helpful){await repo.removeHelpful(widget.flash.id);}else{await repo.markHelpful(widget.flash.id);}setState(()=>helpful=!helpful);}}catch(_){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Action could not be completed.')));}finally{if(mounted)setState(()=>busy=false);}}
@override Widget build(BuildContext context){final f=widget.flash;return Scaffold(appBar:AppBar(title:const Text('Report')),body:ListView(padding:const EdgeInsets.all(20),children:[Text(f.title,style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w700)),if(f.category!=null)...[const SizedBox(height:10),Chip(label:Text(f.category!))],if(f.description!=null)...[const SizedBox(height:18),Text(f.description!)],const SizedBox(height:24),if(f.location?.label!=null)Row(children:[const Icon(Icons.location_on_outlined),const SizedBox(width:8),Expanded(child:Text(f.location!.label!))]),const SizedBox(height:24),Row(children:[_Stat(icon:Icons.thumb_up_outlined,value:f.engagement.helpful.toString()),_Stat(icon:Icons.share_outlined,value:f.engagement.shares.toString()),_Stat(icon:Icons.visibility_outlined,value:f.engagement.views.toString())]),const SizedBox(height:24),Row(children:[Expanded(child:OutlinedButton.icon(onPressed:busy?null:()=>react(false),icon:Icon(helpful?Icons.thumb_up:Icons.thumb_up_outlined),label:Text(helpful?'Helpful':'Helpful'))),const SizedBox(width:12),Expanded(child:OutlinedButton.icon(onPressed:busy?null:()=>react(true),icon:const Icon(Icons.share_outlined),label:const Text('Share')))])]));}}
class _Stat extends StatelessWidget{const _Stat({required this.icon,required this.value});final IconData icon;final String value;@override Widget build(BuildContext context)=>Expanded(child:Column(children:[Icon(icon),const SizedBox(height:6),Text(value)]));}
